---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
  labels: 
    author: eccentric
    type: proxy-server
spec:
  replicas: 2
  selector:
    matchLabels:
      type: proxy-server
  template:
    metadata:
      name: nginx-pod
      labels: 
        author: eccentric
        type: proxy-server
    spec: 
      containers:
        - name: nginx
          image: nginx:1.25
          ports: 
            - containerPort: 80
              hostPort: 8080  

...
