---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ghost-daemonset
  labels: 
    type: proxy
    author: eccentric
spec:
  selector:
    matchLabels: 
      type: proxy
      author: eccentric
  template:
    metadata:
       name: nginx-pod
       labels:
         type: proxy
         author: eccentric
    spec:
      containers:
        - name: mynginx
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 9090  
