---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    author: eccentric
    type: db
spec:
  replicas: 3
  selector:
    matchLabels:
      type: db
  template:
    metadata: 
      name: mysql-pod
      labels:
        author: eccentric
        type: db
    spec:
      containers:
        - name: mydb
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: eccentric


...
