---
apiVersion: v1
kind: Pod
metadata: 
  name: mysql-pod
  labels:
    author: eccentric
    type: mydb
spec:
  containers:
    - name: mydb
      image: mysql:8.0
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: eccentric
...
