---
apiVersion: v1
kind: Pod
metadata:
  name: ghost-pod
  labels: 
    author: eccentric
    type: cms
spec:
  containers:
    - name: myghost
      image: ghost
      env: 
        - name: NODE_ENV
          value: eccentric
...
