---
apiVersion: v1
kind: Pod
metadata:
  name: ghost-pod
  namespace: eccentric-ns
  labels: 
    author: eccentric
    type: cms
spec:
  containers:
    - name: myghost
      image: ghost
      env: 
        - name: NODE_ENV
          value: eccentric
      ports:
        - containerPort: 2368
          hostPort: 3001 
...
