---
apiVersion: v1
kind: ReplicationController
metadata: 
  name: httpd-rc 
  labels: 
    author: eccentric
    type: webserver
spec: 
  replicas: 3
  template:
    metadata:
      name: httpd-pod
      labels: 
        author: eccentric
        type: webserver
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 8888  
...
