---
apiVersion: v1
kind: Pod
metadata: 
  name: httpd-pod
  labels:
    type: webserver
    author: eccentric
spec:
  containers:
    - name: myhttpd
      image: httpd
      resources:
        requests:
          cpu: "250m"
          memory: "64Mi"
        limits:
          cpu: "500m"
          memory: "128Mi"
  tolerations:
    - key: slave2
      value: eccentric2
      operator: Equal
      effect: NoSchedule
...
