---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    type: webserver
    author: eccentric
spec:
  replicas: 2
  selector:
    matchLabels:
      type: webserver
      author: eccentric
  template:
    metadata:
      name: httpd-pod
      labels:
        type: webserver
        author: eccentric
    spec:
      containers:
        - name: myhttpd
          image: httpd
          resources:
            requests:
              cpu: "250m"
              memory: "64Mi"
            limits: 
              cpu: "500m"
              memory: "128Mi"
...
