---
apiVersion: v1
kind: Service 
metadata:
  name: ghost-service
  labels: 
    type: cms
    author: eccentric
spec: 
  type: LoadBalancer
  ports:
    - targetPort: 2368
      port: 2368
      nodePort: 30009
  selector:
    type: cms
    author: eccentric
...
