---
apiVersion: v1
kind: Pod
metadata: 
  name: tomcat-pod
  labels:
    type: appserver
    author: eccentric
spec:
  containers:
    - name: mytomee
      image: tomee
  tolerations:
    - key: slave1
      operator: Equal
      value: eccentric1
      effect: NoSchedule 
...
