---
apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    type: db
    author: eccentric
spec:
  containers:
    - name: myredis
      image: kiranreddy45/redis 
      volumeMounts:
        - name: myvolume
          mountPath: /data/redis
  volumes:
    - name: myvolume
      emptyDir: {}
...
