---
apiVersion: v1
kind: Service
metadata:
  name: postgres-app-service
  labels:
    type: postgres-db
    author: eccentric
spec:
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    type: postgres-db
    author: eccentric
...
