---
apiVersion: v1
kind: Service
metadata:
  name: redis-app-service
  labels:
    type: redis-db
    author: eccentric
spec:
  ports:
    - targetPort: 6379
      port: 6379
  selector:
    type: redis-db
    author: eccentric
    

...
