---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    type: voting-app
    author: eccentric
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30010
  selector:
    type: voting-app
    author: eccentric
...
