---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    type: voting-app
    author: eccentric
spec: 
  replicas: 2
  selector:
    matchLabels:
      type: voting-app
      author: eccentric
  template:
    metadata:
      name: voting-app-pod
      labels: 
        type: voting-app
        author: eccentric
    spec:
      containers:
        - name: my-voting-app
          image: dockersamples/examplevotingapp_vote
...
